title: Taste of Design - Free beginner course to learn about design, prototyping, and testing.
email: info@tasteofcode.nl
description: > # this means to ignore newlines until "baseurl:"
  Come and have a Taste of UX Design together.
  From the creators of Taste of Code. You can now dive into the world of User Experience Design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tasteofdesign.nl" # the base hostname & protocol for your site
twitter_username: TasteofUX
github_username:  codaisseur

# Build settings
markdown: kramdown
destination: ./_site
exclude: ['scss','Gem*','Guard*','*.rb','.sass-cache','.git*','config.rb','sass','stylesheets','javascripts','README.md','.jekyll-metadata']
